language: python
cache: pip
sudo: false
dist: xenial
matrix:
  include:
  - python: '3.6'
    env: TOXENV=lint
  - python: '3.6'
    env: TOXENV=manifest
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
  - python: pypy
    env: TOXENV=pypy
    dist: trusty
  - python: pypy3
    env: TOXENV=pypy3
    dist: trusty
install:
- pip install tox
before_install:
- pip install python-coveralls
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
